source 'https://rubygems.org'

gem 'bourbon'
gem 'jekyll', '~> 2.5.3'
gem 'jekyll-assets'
gem 'jekyll-sitemap', '~>0.6.0'
gem 'jekyll-redirect-from'
gem 'neat'
gem 'rouge'
gem 's3_website'
gem 'therubyracer'
gem 'rubocop'
