# Site settings
title: downey.io
name: Tim Downey
description: "Personal blog containing thoughts on software development, lifelong learning, photography, etc."
keywords:
  - tim downey software engineer
  - tim downey
  - programming blog
  - ruby
  - omscs blog
  - software development
baseurl: ""
url: "https://downey.io"

# Build settings
highlighter: rouge
paginate: 20
paginate_path: "blog/:num"
permalink: "blog/:title/"

exclude:
  - s3_website.yml
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

assets:
  sources:
    - _assets/javascripts
    - _assets/stylesheets

collections:
  notes:
    output: true
